set backup
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
syntax off
set vb
set noeb
set gcr=n:blinkon0
set tabstop=8
set softtabstop=8
set shiftwidth=8
set shiftround
set noexpandtab
set autoindent
set encoding=utf8
set hidden
set history=1000
set undolevels=1000
set title

